image: Visual Studio 2022
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
before_build:
- cmd: dotnet restore
build:
  parallel: true
  verbosity: minimal
artifacts:
  - path: 'ObservableCollectionEx\bin\Release\ObservableCollectionEx.*.nupkg'
    name: ObservableCollectionEx 
