version: 1.4.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: ObservableCollectionEx\bin\Release\ObservableCollectionEx.0.0.0.nupkg
  name: ObservableCollectionEx.$(APPVEYOR_BUILD_VERSION).nupkg
  
